### ISSUE TITLE
UX mockups for branded Coming Soon holding page

### ISSUE THREAD

**Issue by krissy** [empowerhack/DrawMyLife-Website#48]
## What

Now we have a confirmed domain drawmylife.org, we want to point it to a branded holding page for comms while the team site is being built. This ticket covers UX design of this page that devs can use for build reference.

## To Do
* @rocioleon @EChesters to have initial chat and coordinate on this.

**Comment by rocioleon** [comment]
Desktop and mobile devices design

**Comment by rocioleon** [comment]
![dml-cover-page-03](https://cloud.githubusercontent.com/assets/18365496/24590688/7c2fa1be-17e9-11e7-94c4-9809a785c3c2.jpg)
![dml-cover-page-04-hover-effect](https://cloud.githubusercontent.com/assets/18365496/24590689/7c3163b4-17e9-11e7-8ec4-f6d56d24a036.jpg)

**Comment by rocioleon** [comment]
I thought we could include a 'Get Notified' button which popup a simple dialog to collect email address and name (which I haven't done yet in case this is not what we want). By doing this, we get database and measure how many people are interesting in this project for further promotion.

**Comment by rocioleon** [comment]
@CathMollie, please check text to keep consistency with your copy

NOte: the drawing is an edited version. Can we use it? Otherwise I need to know what type of imagery we have available for the web

**Comment by CathMollie** [comment]
Hi @rocioleon this looks great.
- we still need to confirm our tagline. Shameful that I forgot about this cos @echesters started work on this.
- Drawing is anonymised so fine but I also think looks good without.
- Great idea on mailing list.

**Comment by krissy** [comment]
Thanks @rocioleon! This looks great :D

We made some progress on this in #49 and also have a couple of questions:

- Do we have any wireframes for the mobile/responsive view of this page? The background image doesn't quite work on small, vertical screens.
- We don't have a mechanism just yet to collect addresses for a mailing list, and we didn't think / are hoping the holding page will not be up for very long to warrant the effort to configure this, so we thought a nice middle ground will be the button turning into a Contact Us and linking to our email address. What do you think of this fallback?

**Comment by rocioleon** [comment]
@krissy 

- There is not responsive wireframe at the moment because I needed to ensure that we are happy with it and we can use that image. I will work on it this week.

- I thought it could be difficult to set up the mailing list but better to ask in any case. I am happy with the decision you guys make about it.

**Comment by krissy** [comment]
Thanks @rocioleon, looking forward to see the responsive design!

**Comment by rocioleon** [comment]
Hi team,
After re-visit the imagery we are using currently in other documents and presentations, I thought it would make more sense to keep consistency across all DML points.

### **To be completed by developer and anyone else who can help with the following:**
- Include EmpowerHack logo in white and link to website
- Complete footer with copyright and any formal information that needs to be included as terms and conditions if needed
- Photo source: Credit Rachel Unkovic International Rescue Committee Flickr
- Text on screen needs to be reviewed and sign off by Cath as she is the one doing the copy

**### Design for Desktop +1200, portrait tablet and portrait phone** 
Please note that I've exported the files with Axure and it is not very good at that so quality is low but the real preview it looks good, promise!!

![dml-cover-desktop 1200](https://cloud.githubusercontent.com/assets/18365496/25441125/45e9ba1e-2a99-11e7-811b-5462ca3f83de.png)
![dml-cover-portrait-phone](https://cloud.githubusercontent.com/assets/18365496/25441126/45eb5860-2a99-11e7-820c-66b4ec890127.png)
![dml-cover-portrait-tablet](https://cloud.githubusercontent.com/assets/18365496/25441124/45e9c18a-2a99-11e7-8cfd-a811aecde43c.png)

### All files including psd. in case you guys need to amend anything else
https://drive.google.com/drive/folders/0BywYxaOTU-6uMUVpbU4yLUVUT00

**Comment by krissy** [comment]
Really great work @rocioleon, thanks for the detail. :+1:

**Comment by krissy** [comment]
Done 🙌
